filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: https://hazem-internship.github.io/gow-new-1/
releases:
- chart: dev/gow-new-1
  version: 0.0.10
  name: gow-new-1
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
