apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        hazem-internship/gow-new-1: true
        hazem-internship/k3s-ubuntu-dev: true
        hazem-internship/spring: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        hazem-internship/gow-new-1: merge
        hazem-internship/k3s-ubuntu-dev: merge
        hazem-internship/spring: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - hazem-internship/k3s-ubuntu-dev
        - hazem-internship/gow-new-1
        - hazem-internship/spring
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - hazem-internship/k3s-ubuntu-dev
        - hazem-internship/gow-new-1
        - hazem-internship/spring
      target_url: http://lighthouse.jx.10.0.0.222.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
