apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: hazem-internship
    provider: github
    repository: gow-new-1
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: hazem-internship-gow-new-1
  namespace: jx
spec:
  httpCloneURL: https://github.com/hazem-internship/gow-new-1.git
  org: hazem-internship
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: gow-new-1
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/hazem-internship/gow-new-1
